src/TableNodesSpecs.js

This diff supports transparent borders, which google implements as block borders with width of `0pt`. I've also added a check for `0px` just for robustness, but it might not be necessary (no real way to check)

fix border color

---

dist/ui/PopUpPosition.js
dist/ui/PopUpPosition.js.flow
src/ui/PopUpPosition.js

I created some examples to test by messing with the toolbar config (those changes aren't in this diff)
showing bottom-centered menu continuing to operate as normal
Showing non-overflow left bottom-centered menu:
@hedgerwang , if you approve of this I'll add a commit on top that rebuilds `/dist` and then merge

prevent center popover from floating offscreen left

---

src/TextAlignCommand.js

Current bug: On alignment, nodes revert back to default behaviour
GIF
That was because we weren't merging the orignal node attributes with the new `align` attribute

preserve original attributes on text align command

---

dist/ui/FontSizeCommandMenuButton.js
dist/ui/FontSizeCommandMenuButton.js.flow
src/ui/FontSizeCommandMenuButton.js

Note: I'll fix up the submenu alignment in a follow-up diff after we update our positioning options.

[fix] Swap 10 and 11 in font size menu.

---

dist/TextAlignCommand.js
dist/TextAlignCommand.js.flow
dist/ui/PopUp.js
dist/ui/PopUp.js.flow
dist/ui/PopUpPosition.js
dist/ui/PopUpPosition.js.flow
dist/ui/TooltipSurface.js
dist/ui/TooltipSurface.js.flow
dist/ui/czi-tooltip-surface.css
src/ui/PopUp.js
src/ui/PopUpPosition.js
src/ui/TooltipSurface.js
src/ui/czi-tooltip-surface.css

As discussed offline, this reverts the changes to `atAnchorBottom` and renames it to `atAnchorBottomLeft` for clarity. It switches the tooltip to using `atAnchorBottomCenter`.

Clean up at anchor bottom

---

dist/TextAlignCommand.js
dist/TextAlignCommand.js.flow
dist/ui/czi-tooltip-surface.css
src/ui/czi-tooltip-surface.css

Before: (shows "Left Align" at top right)
After:

[fix] Don't show tooltips in print mode

---

dist/isEditorStateEmpty.js
dist/isEditorStateEmpty.js.flow
src/isEditorStateEmpty.js

Placeholder wasn't showing for " " content (the default) since the text node was passing the `isAtom` case.
Fix:

[fix] Update empty check since text node can be an atom

---

dist/ui/Editor.js
dist/ui/Editor.js.flow
src/ui/Editor.js

This will be used for custom transformations upon paste, such as removing marks from comments that only exist in a different doc.

Take in function for transforming pasted HTML

---

dist/FontSizeMarkSpec.js
dist/FontSizeMarkSpec.js.flow
dist/convertToCSSPTValue.js
dist/convertToCSSPTValue.js.flow
dist/ui/FontSizeCommandMenuButton.js
dist/ui/FontSizeCommandMenuButton.js.flow
src/FontSizeMarkSpec.js
src/convertToCSSPTValue.js
src/ui/FontSizeCommandMenuButton.js

Original test case from demo doc:
Pasted and rounded:
Test HTML to paste with various font sizes:
Pasted and rounded:

Round font sizes to nearest valid font size.

---

dist/EditorPageLayoutPlugin.js
dist/EditorPageLayoutPlugin.js.flow
src/EditorPageLayoutPlugin.js

We're missing various styling like `min-height` when we don't include `data-layout`

Always include data-layout attribute.

---

dist/EditorPageLayoutPlugin.js
dist/EditorPageLayoutPlugin.js.flow
src/EditorPageLayoutPlugin.js

Reverting since the original PR wasn't ready to merge.

Revert "Always include data-layout attribute."

---

dist/TablePlugins.js
dist/TablePlugins.js.flow
dist/createTableResizingPlugin.js
dist/createTableResizingPlugin.js.flow
dist/ui/czi-table.css
src/TablePlugins.js
src/createTableResizingPlugin.js
src/ui/czi-table.css

I noticed in `latest` that there was something getting repeatedly logged in the console. Also noticed the filename typo when I was cleaning up the console.log. @hedgerwang we should consider consistent code reviews for this repo as well.

Fix typos and remove console.log in table resizing plugin

---

dist/ui/czi-editor.css
src/ui/czi-editor.css

Following up on https://github.com/chanzuckerberg/czi-prosemirror/pull/37 and https://github.com/chanzuckerberg/czi-prosemirror/commit/153bf84c17b70d555a9c8f991e07406d02edec6b

Only apply default min-height to editor pages

---

dist/toSafeHTMLDocument.js
dist/toSafeHTMLDocument.js.flow
src/toSafeHTMLDocument.js

`document.write` was not working properly in Firefox. 
Security of `innerHTML` - https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#Security_considerations
The `innerHTML` spec specifies that `<script>` should not execute, but there can still be other risks. This is at least matching what `prosemirror` is doing: 
https://github.com/ProseMirror/prosemirror/issues/473#issuecomment-255727531
https://github.com/ProseMirror/prosemirror-view/commit/0f9d341d30175bab77670ef8016c8b25079b56d6
Verified that copy-paste now works in Firefox (attached). Also verified in Safari and Chrome

[fix] Fix copy-paste within doc in Firefox

---

src/ui/czi-editor.css
src/ui/czi-list.css
src/ui/czi-table.css
src/ui/czi-vars.css

- reduce the default page padding to match the google doc's layout
- reduce the default margin of <ol /> and <ul /> to match google doc's layout
- fix table row style in printing mode.
**before**
**after**

[EASY] Tweak styles

---

build_bin.py

The recent the clean up works rename the script command `build_bin` to `app:build`.
This fixes the tool that calls the script.

[EASY] Fix script that builds the demo assets.

---

src/ui/MathInlineEditor.js
src/ui/MathNodeView.js

For now, opening the equation editor will take the focus away from the selected math element, which causes the equation editor to be closed again because the math element is not active.
This diff ensures that the math element can stay as active while user is editing the math content.

Fix math editor

---

.eslintrc
src/TableNodesSpecs.js
src/TablePlugins.js
src/TableResizePlugin.js
src/ui/czi-table.css

- resizing one column might make the table wider than the page's width
- resizing one column might affect multiple width of other columns.
DEMO: https://cdn.summitlearning.org/assets/czi_prosemirror_0_0_1_1_20190321135443_index.html
---
- the table 's width is constraint within page's width.
- user now can resize the left and right margin of the table.
DEMO: http://cdn.summitlearning.org/assets/czi_prosemirror_0_0_1_1_20190426231825_index.html

Use custom column resizing plugin.

---

dist/TableResizePlugin.js
dist/TableResizePlugin.js.flow
src/TableResizePlugin.js

**About**
After resizing the table, it should also update the attributes of the the table. 
For now, only the DOM element is updated, but table's attributes remain the same.
**Test Plan**
- go http://localhost:3001/convert.html
- insert a table
- resize the columns and left margin
- click "ProseMirror => JSON"
- verify that the JSON data is updated after resizing.

Fix table resizing with margin-left.

---

dist/TableResizePlugin.js
dist/TableResizePlugin.js.flow
package-lock.json
package.json
src/TableResizePlugin.js

The default package of  "prosemirror-tables" does not export some utility functions that we need.
As a quick workaround, I forked the package and exports more utility functions that we need in https://github.com/chanzuckerberg/prosemirror-tables/commit/798082376c83f176231ff25589a944f64d24cb5a
The long term solution would be sending out an official PR to request the official "prosemirror-tables" to accept my changes and publish a new NPM version, but before that happen, we could just use the forked version.

Use forked "prosemirror-tables"

---

demo/UIExamples.js
dist/ui/mathquill-editor/MathQuillEditor.js
dist/ui/mathquill-editor/MathQuillEditor.js.flow
dist/ui/mathquill-editor/MathQuillEditorSymbols.js
dist/ui/mathquill-editor/MathQuillEditorSymbols.js.flow
dist/ui/renderLaTeXAsHTML.js
dist/ui/renderLaTeXAsHTML.js.flow
package-lock.json
package.json
src/ui/mathquill-editor/MathQuillEditor.js
src/ui/mathquill-editor/MathQuillEditorSymbols.js
src/ui/renderLaTeXAsHTML.js

Per request from users, we need to clean up some math symbols and add more symbols.
This diff updates the symbols used in math editor.
| before | after |
|---|---|
| ![image](https://user-images.githubusercontent.com/1504439/57163573-76677080-6da6-11e9-8f7a-84c2c9bfcc57.png) ![image](https://user-images.githubusercontent.com/1504439/57163625-939c3f00-6da6-11e9-917a-6b03fb725615.png) | ![image](https://user-images.githubusercontent.com/1504439/57163605-8717e680-6da6-11e9-8455-9109bccce384.png) ![image](https://user-images.githubusercontent.com/1504439/57163647-a151c480-6da6-11e9-98b2-b67cd6049bc4.png) | 
|---|---|

Clean up Math Symbols in Math Editor

---

dist/ParagraphNodeSpec.js
dist/ParagraphNodeSpec.js.flow
dist/TextLineSpacingCommand.js
dist/TextLineSpacingCommand.js.flow
dist/patchStyleElements.js
dist/patchStyleElements.js.flow
dist/ui/czi-vars.css
dist/ui/toCSSLineSpacing.js
dist/ui/toCSSLineSpacing.js.flow
src/ParagraphNodeSpec.js
src/TextLineSpacingCommand.js
src/patchStyleElements.js
src/ui/czi-vars.css
src/ui/toCSSLineSpacing.js

The current value "1" that represents the "single line spacing" is too small for proper readability.
We should calibrate it and use "1.25" instead.
Also the, Google has been incorrectly exporting "1.15" for "single line spacing" while Google Doc itself uses "1.25" for "single line spacing" 
This PR calibrates the value that used to represents the  "single line spacing".
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/1504439/57491380-8208da80-7271-11e9-8d86-f9609e0eee18.png) | ![image](https://user-images.githubusercontent.com/1504439/57491406-9947c800-7271-11e9-845a-376d66d1b602.png)  |

Calibrate line-spacing value.

---

dist/ImageNodeSpec.js
dist/ImageNodeSpec.js.flow
src/ImageNodeSpec.js

The logic that detects cropped image checks `marginLeft` and `marginTop`. If both `marginLeft` and `marginTop` are present, it thinks that the image is cropped.
However, to check whether `marginLeft` and `marginTop` are present, it should not only perform nullity check, it shall also check if the value means "empty" (e.g. "0px").
- copy HTML from https://gist.github.com/hedgerwang/67845c04e0825bc08809b40607fb6ca6
- paste conversion in http://localhost:3001/convert.html
- verify that the images at the doc is resize-able.

[easy] Fix logics that detects cropped image.

---

CODEOWNERS

GitHub CODEOWNERS file is a simple way to automate away some of the pain associated with the review system on github, by automatically assigning reviewers to a pull request based on which files were modified.
more about the setup
https://github.com/chanzuckerberg/czi-prosemirror/compare/add_code_owners?expand=1

Using Github CODEOWNERS file

---

dist/ui/LinkTooltip.js
dist/ui/LinkTooltip.js.flow
dist/ui/czi-link-tooltip.css
src/ui/LinkTooltip.js
src/ui/czi-link-tooltip.css

Per feedback from users, make the UI that navigates to  a bookmark less confusing.
| Before| After (For Link) | After (For Bookmark) |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/1504439/57493718-0744bd00-727b-11e9-84cd-bd890f6b2eb9.png) | ![image](https://user-images.githubusercontent.com/1504439/57493769-35c29800-727b-11e9-90de-b9d12c7a2013.png)| ![image](https://user-images.githubusercontent.com/1504439/57493743-1af02380-727b-11e9-897d-f8cd5874de7b.png)
|

Update UI for navigating to a  bookmark.

---

dist/ui/findActiveFontType.js
dist/ui/findActiveFontType.js.flow
src/ui/findActiveFontType.js

The `FontFaceSet.check` was failing for monospace and Lucida Console, so the menu would show "Arial" even though the font was successfully set. monospace works if you remove the `"` around the font check, but Lucida Console still didn't work if you remove the quotation marks.

Fix font type menu for monospace and Lucida Console.

---

dist/TableResizePlugin.js
dist/TableResizePlugin.js.flow
src/TableResizePlugin.js

When a table element is being resized, we should only check its own column elements, not all the column elements within.
This addresses the issue reported at  #73

Fix resizing nested tables.

---

dist/TextLineSpacingCommand.js
dist/TextLineSpacingCommand.js.flow
dist/ui/czi-vars.css
dist/ui/toCSSLineSpacing.js
dist/ui/toCSSLineSpacing.js.flow
src/TextLineSpacingCommand.js
src/ui/czi-vars.css
src/ui/toCSSLineSpacing.js

I just realized that all the line spacing values exported by Google can't be used directly. 
After doing a precise measurement of different line spacing values exported from Google, I update our own logic that normalized the line spacing values. 
Also, I change the default line spacing value from "125" to "138%", so it uses the same line spacing value as Google dos.

Calibrate line spacing values.

---

dist/FontSizeMarkSpec.js
dist/FontSizeMarkSpec.js.flow
dist/ParagraphNodeSpec.js
dist/ParagraphNodeSpec.js.flow
dist/ui/czi-editor.css
src/FontSizeMarkSpec.js
src/ParagraphNodeSpec.js
src/ui/czi-editor.css

In editor, the CSS `line-height` is applied at the block (e.g. a paragraph) level and `font-size` is applied at inline (e.g. a span) level.
```
<p style="line-height: 200%">
foo <span style="font-size: 20pt">bar</span>
</p>
```
and there causes a but that the  inline  element with custom font-size does not get its line-height rendered properly because it uses the same line-height as the containing block element does instead of computing it own line-height.
This diff ensures that element with custom font size will compute its own line-height correctly.
- select some paragraph
- set line spacing to "double"
- select some text
- set font-size to large font size.

Fix: Element with custom font size should compute its own line-height correctly.

---

dist/OrderedListNodeSpec.js
dist/OrderedListNodeSpec.js.flow
dist/consolidateListNodes.js
dist/consolidateListNodes.js.flow
dist/splitListItem.js
dist/splitListItem.js.flow
src/OrderedListNodeSpec.js
src/consolidateListNodes.js
src/splitListItem.js

Due to popular requests from users, we'd like to allow user to split lists without breaking the counter's order.
For now, if user presses the ENTER key at an empty list item between a list, it will split the list and each list resets it own counter.
So this list 
---
---
becomes two lists that are separate by a new paragraph.
---
---
With this PR, the split lists that are by the non-list blocks (e.g. paragraph)  can still share the same counter.
---
---
so user will be easily to insert block contents between list items
For example, 
---
---
DEMO
---
---

Allow split lists to share the same counter variable.

---

dist/TableResizePlugin.js
dist/TableResizePlugin.js.flow
src/TableResizePlugin.js

After resizing a cell that spans multiple columns, the table's layout will appear broken (e.g. wider or narrower than expected).
- Test the following snippet https://gist.github.com/hedgerwang/f453d8370b004047cc33bf91929b596f
- Test with url http://localhost:3001/convert.html
| Before | After |
|---|---|
| Resizing a simple table works fine, but resizing a table with merged cells will end up with wrong layout | Works as expected |
|![before](https://user-images.githubusercontent.com/1504439/58723807-d47c7900-838f-11e9-8203-345851110677.gif)|![after](https://user-images.githubusercontent.com/1504439/58723565-3b4d6280-838f-11e9-8139-08a9a968046c.gif)|

[FIX] Resizing table with merged cells should work as expected.

---

.eslintrc
dist/ListItemNodeSpec.js
dist/ListItemNodeSpec.js.flow
dist/patchListElements.js
dist/patchListElements.js.flow
dist/ui/Editor.js
dist/ui/Editor.js.flow
dist/ui/ListItemNodeView.js
dist/ui/ListItemNodeView.js.flow
dist/ui/czi-bullet-list.css
dist/ui/czi-list.css
src/ListItemNodeSpec.js
src/patchListElements.js
src/ui/Editor.js
src/ui/ListItemNodeView.js
src/ui/czi-bullet-list.css
src/ui/czi-list.css

List item's counter should use the same style (e.g. color and font size) as its content.
| Before | After |
|---|---|
| Counter does not use the same style as its content | Counter uses the same style |
| ![image](https://user-images.githubusercontent.com/1504439/58735765-554b6d00-83b0-11e9-986c-61d5d8abb616.png)|![image](https://user-images.githubusercontent.com/1504439/58735779-62685c00-83b0-11e9-8619-b69254f97a7d.png)|

[FIX]: List counter's style should match its content.
